#![no_std]
#![no_main]

use panic_halt as _;// panic handler. underscore syntax means we are using without giving the local name.
use cortex_m_rt::entry;//runtime. marks main fn as program's entry point
use cortex_m::delay::Delay;//use system timer peripheral to produce accurate delays
use stm32f1xx_hal::{
    pac,//peripheral access crate generated by system view description language (SVD) file. pac has dp (device peripherals: uart, gpio) and cp (core peripherals: nvic, systick) modules
    prelude::*,//import commonly used traits and types eg _embedded_hal traits, extention traits for gpio and rcc, digital io traits etc
};

const DELAY_MS: u32 = 7000;
#[entry]
fn main() -> ! {//fn never returns
    let dp = pac::Peripherals::take().unwrap();//take ownership of the device peripherals. returns an option, so we unwrap it to get the peripherals. if we try to take the peripherals again, it will return None, preventing multiple ownership and ensuring safe access to hardware resources.
    let cp = cortex_m::Peripherals::take().unwrap();//access cp from processor core

    let mut flash = dp.FLASH.constrain();//convert to high level type safe interface. constrain() method converts the raw peripheral into a higher-level abstraction that provides safe access to the peripheral's functionality. In this case, it converts the FLASH peripheral into a type that allows us to configure and control the flash memory settings safely.
    let rcc = dp.RCC.constrain();
    let clocks = rcc.cfgr
        .use_hse(8.MHz())//use external crystal oscillator as clock source. HSE: high speed external. 8.mhz() is a method that converts 8 into a frequency type representing 8 MHz. This is important for setting the correct clock speed for the microcontroller, which affects the timing of all operations.
        .sysclk(72.MHz())
        .freeze(&mut flash.acr);//configure and freeze the clock settings. cfgr is the clock configuration register, and freeze applies the configuration and returns a Cl. set HSI/HSE/PLL as system clock source. includes config for different buses eg ABP
    //flash.acr is the access control register for flash memory, which may need to be configured based on the clock settings to ensure proper operation of the flash memory. freezing the clock configuration means that we are finalizing the clock settings and they cannot be changed afterward. this is important for ensuring stable and predictable behavior of the system.
    // When you call .freeze() without specifying a crystal speed, the hardware abstraction layer (HAL) defaults to using the internal RC oscillator (usually 8 MHz). However, Blue Pill boards have an external 8 MHz crystal oscillator on board that can be boosted up to 72 MHz via the internal PLL (Phase-Locked Loop).
    //gpio setup:
    let mut gpioc = dp.GPIOC.split();
    //led variable:
    let mut led = gpioc.pc13.into_push_pull_output(&mut gpioc.crh);//pc13 is pin no. crh: config register high
    let mut delay = Delay::new(cp.SYST, clocks.sysclk().to_Hz());
    // On the Blue Pill board, the onboard LED at PC13 is wired up via an inverted (active-low) configuration; led.set_high() turns the LED off, and led.set_low() turns it on. This is because the LED is connected between the power supply (Vcc) and the pin, so setting the pin low allows current to flow through the LED to ground, illuminating it.
    loop {
        led.set_high();
        delay.delay_ms(DELAY_MS);
        led.set_low();
        delay.delay_ms(DELAY_MS);
    }
}
